services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3305:3305"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: react-app
    tty: true
    stdin_open: true
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    volumes:
      - .:/enviroment_to_try
  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444
volumes:
  mysql_volume:
networks:
  app-network:
    driver: bridge
